query OrgTierById($id:UUID!) {
  orgTierById(id:$id) {
    id
    nameEn
    nameFr
    primaryDomain
    retiredAt
    tierLevel
    parentOrganizationTier {
      id
      nameEn
      nameFr
    }
    organization {
      id
      nameEn
      nameFr
    }
    owner {
      id
      person {
        id
        givenName
        familyName
        email
      }
    }
    childOrganizationTier {
      id
      nameEn
      nameFr
      retiredAt
      headcount
      totalEffort
      owner {
        id
        person {
          id
          givenName
          familyName
        }
      }
    }
    headcount
    totalEffort
    capabilityCounts {
      name
      domain
      level
      counts
    }
    teams {
      id
      nameEnglish
      nameFrench
      headcount
      totalEffort
      vacantRoles {
        id
      }
      owner {
        id
        person {
          id
          givenName
          familyName
        }
      }
    }
  }
}