query OrganizationById($id:UUID!) {
  organizationById(id:$id) {
    id
    nameEn
    nameFr
    acronymEn
    acronymFr
    orgType
    url
    retiredAt
    topOrgTier {
      id
      nameEn
      nameFr
      primaryDomain
      headcount
      totalEffort
      owner {
        id
        person {
          id
          givenName
          familyName
          email
        }
      }
    }
    capabilityCounts {
      domain
      name
      level
      counts
    }
    affiliations {
      id
      affiliationRole
      organization {
        id
        nameEn
      }
      person {
        id
        givenName
        familyName
      }
    }
  }
}